remote_theme: Sylhare/Type-on-Strap

title: Waypoint Bioinformatics                 # Name of website
avatar: " "       # Path of avatar image, to be displayed in the theme's header
description: Coming Soon            # Short description, primarily used by search engines

header_text: Welcome to Waypoint Bioinformatics 
header_feature_image: assets/img/waypoint2.png 
footer_text: Copyright 2020



